<?php

namespace ContainerNQE1ZQL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M43_53OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M43.53O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M43.53O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'AllocationRepository' => ['privates', 'App\\Repository\\AllocationRepository', 'getAllocationRepositoryService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'AllocationRepository' => 'App\\Repository\\AllocationRepository',
            'managerRegistry' => '?',
        ]);
    }
}
