<?php

namespace ContainerMSG4B97;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RQytWjSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rQytWjS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rQytWjS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'allocationRepository' => ['privates', 'App\\Repository\\AllocationRepository', 'getAllocationRepositoryService', true],
        ], [
            'allocationRepository' => 'App\\Repository\\AllocationRepository',
        ]);
    }
}
