<?php

namespace ContainerMSG4B97;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZmwmPKjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zmwmPKj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zmwmPKj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AllocationController::addformallocation' => ['privates', '.service_locator.JFWvM5G', 'get_ServiceLocator_JFWvM5GService', true],
            'App\\Controller\\AllocationController::deleteauthor' => ['privates', '.service_locator.M43.53O', 'get_ServiceLocator_M43_53OService', true],
            'App\\Controller\\AllocationController::editallocation' => ['privates', '.service_locator..MaPObv', 'get_ServiceLocator__MaPObvService', true],
            'App\\Controller\\AllocationController::indexadmin' => ['privates', '.service_locator.bMcwNe.', 'get_ServiceLocator_BMcwNe_Service', true],
            'App\\Controller\\AllocationController::showdballocation' => ['privates', '.service_locator.rQytWjS', 'get_ServiceLocator_RQytWjSService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\AllocationController:addformallocation' => ['privates', '.service_locator.JFWvM5G', 'get_ServiceLocator_JFWvM5GService', true],
            'App\\Controller\\AllocationController:deleteauthor' => ['privates', '.service_locator.M43.53O', 'get_ServiceLocator_M43_53OService', true],
            'App\\Controller\\AllocationController:editallocation' => ['privates', '.service_locator..MaPObv', 'get_ServiceLocator__MaPObvService', true],
            'App\\Controller\\AllocationController:indexadmin' => ['privates', '.service_locator.bMcwNe.', 'get_ServiceLocator_BMcwNe_Service', true],
            'App\\Controller\\AllocationController:showdballocation' => ['privates', '.service_locator.rQytWjS', 'get_ServiceLocator_RQytWjSService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\AllocationController::addformallocation' => '?',
            'App\\Controller\\AllocationController::deleteauthor' => '?',
            'App\\Controller\\AllocationController::editallocation' => '?',
            'App\\Controller\\AllocationController::indexadmin' => '?',
            'App\\Controller\\AllocationController::showdballocation' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AllocationController:addformallocation' => '?',
            'App\\Controller\\AllocationController:deleteauthor' => '?',
            'App\\Controller\\AllocationController:editallocation' => '?',
            'App\\Controller\\AllocationController:indexadmin' => '?',
            'App\\Controller\\AllocationController:showdballocation' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
