<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMSG4B97\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMSG4B97/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMSG4B97.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMSG4B97\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMSG4B97\App_KernelDevDebugContainer([
    'container.build_hash' => 'MSG4B97',
    'container.build_id' => '58397aa1',
    'container.build_time' => 1707819668,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMSG4B97');
